'use strict'

const RISK_WEIGHTS = {
  TAB_HIDDEN: 5,
  WINDOW_BLUR: 2,
  FULLSCREEN_EXITED: 8,
  COPY: 2,
  PASTE: 3,
  CAMERA_STOPPED: 10,
  CAMERA_PERMISSION_DENIED: 10,
  SCREEN_SHARE_STOPPED: 10,
  SCREEN_SHARE_PERMISSION_DENIED: 10,
  NETWORK_DISCONNECTED: 0,
  HEARTBEAT: 0
}

const RISK_LEVELS = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
}

const RISK_THRESHOLDS = {
  MEDIUM: 20,
  HIGH: 40,
  CRITICAL: 70
}

const CONNECTION_STATUS = {
  CONNECTED: 'CONNECTED',
  UNSTABLE: 'UNSTABLE',
  DISCONNECTED: 'DISCONNECTED',
  RECONNECTED: 'RECONNECTED'
}

const SESSION_STATUS = {
  CREATED: 'CREATED',
  SYSTEM_CHECK: 'SYSTEM_CHECK',
  ACTIVE: 'ACTIVE',
  PAUSED: 'PAUSED',
  ENDED: 'ENDED',
  EXPIRED: 'EXPIRED',
  ERROR: 'ERROR'
}

const INCIDENT_SEVERITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
}

const INCIDENT_STATUS = {
  OPEN: 'OPEN',
  UNREVIEWED: 'UNREVIEWED',
  REVIEWED: 'REVIEWED',
  DISMISSED: 'DISMISSED',
  CONFIRMED: 'CONFIRMED'
}

const REVIEW_DECISION = {
  NO_ISSUE: 'NO_ISSUE',
  SUSPICIOUS: 'SUSPICIOUS',
  VIOLATION: 'VIOLATION'
}

const MEDIA_TYPES = {
  WEBCAM_SNAPSHOT: 'WEBCAM_SNAPSHOT',
  EVENT_SNAPSHOT: 'EVENT_SNAPSHOT',
  START_SNAPSHOT: 'START_SNAPSHOT',
  FINAL_SNAPSHOT: 'FINAL_SNAPSHOT'
}

const MEDIA_STATES = {
  REQUESTED: 'REQUESTED',
  UPLOADING: 'UPLOADING',
  UPLOADED: 'UPLOADED',
  VERIFIED: 'VERIFIED',
  FAILED: 'FAILED',
  EXPIRED: 'EXPIRED',
  DELETED: 'DELETED'
}

const HEARTBEAT_THRESHOLD_MS = 30000 // 30 seconds threshold before marking UNSTABLE

module.exports = {
  RISK_WEIGHTS,
  RISK_LEVELS,
  RISK_THRESHOLDS,
  CONNECTION_STATUS,
  SESSION_STATUS,
  INCIDENT_SEVERITY,
  INCIDENT_STATUS,
  REVIEW_DECISION,
  MEDIA_TYPES,
  MEDIA_STATES,
  HEARTBEAT_THRESHOLD_MS
}
